### ISSUE TITLE
Weekly DEV Team Meeting | 31 Jan 2024 #1042

### ISSUE THREAD

**Issue by vaneath** [channainfo/commissioner#1066]
Meeting: Wed, 31 January  2024

+ Sopanha:
	- WIP integrate Google Analytic
	- WIP write document about how to integrate GA4
	- Current issue, GA4 real time is not working properly
	- May try: Should try to use debug mode for android and iOS

+ Leak: M x 1 (#1043), M x 1 (WIP #1050)
	- Should reuse existing partial
	- Human center design should follow existing flow
	- New ui may need to learn and explore new experience
	- Check more about spree_backend
	- Comment if decorate new ui, example spree partial doesn’t exist

+ Nenghak: M x 1 (#1083), S x 1 (#1094), S x 1 (WIP) 
	- Dummy data should be match with context
	- Mark all should be separate
	- Should have name event
	- Add total text for check in quantity
	- Always check consistency 
	- Only demo relevant in issue
	- Should have number in sequence 
	- Display all ticket of current event or all other event
	- Should understand ui more, and how it works with logic
	- Should split previous event and all event separately
	- Switch user is a bit confused 
	- Display screen by order
	- Content should only display to what the issue or pull request  is about

	- Convert svg to icon font (ttf)
	- Font is pre calculate and a lot
	- Svg is slow when convert to complicate font
	- Should not convert svg to font
	- Should upload image to solution for easy understanding
	- Font is not prefer using svg

+ Panha: M x 1 (#1058),  M x 1 (#1091)
	- Request only when you need with push notifications 
	- If onboarding screen is not needed push notifications than no need
	- Should display push notifications if the screen is relevant to push
	- Can show notification if it have notification push screen
	- Some case can you local push by setting schedules 
	- Notifications can be narrow down

+ Moch: (#1066)
	- Long text when using eclipse is not good, so customer doesn’t understand
	- Fix spacing like padding
	- Should change text size, so it can be read
	- Flutter widget can auto fit size to screen
	- Check plural like: hotels, events have ( s ) 
	- Test data with context

+ Vaneath: so far, so good

+ Sokleng: amazing!!

**Comment by theachoem** [comment]
Sopanha:
- S (bmb)
- Doing L (bmp) (Google Analytic GA4)
  - Problem: on IOS, on Android
  - Recheck attributes
  - Debug mode
  - Finish Deeplink

Sreyleak:
M1 , M1(wip) in commissioner
- Problem:
   Rendering partial

Neng hak
M1 , S1 , S1 (wip)
- Put name in Dashboard
- Demo only relavant
- Extract check-in detail from previous event issue
- Design = creativy
- Developer - we = think of logic
- Why extracted svg to font?

Panha:
- M commissioner
- M Request permission
- Next: Event push before channel (server side)

Sreymoch:
L (contrinue from previous week)
L Change to dynamic 

vaneath
S, M

sokleng
M , L WIP

**Comment by theachoem** [comment]
Moderator for each week:

Week 1:
Thea

Week 2:
Panha

Week 3:
Sokleng

Week 4:
Moch

Week 5:
Leak

Week 6:
Nenghak

Week 7:
Vaneath

Week 8:
Panha
