### ISSUE TITLE
Weekly DEV Team Meeting | 07 Feb 2024 #1066

### ISSUE THREAD

**Issue by Sreyleak-Deth** [channainfo/commissioner#1094]
1. sreyleak
- M2(commisioner)
- M1(inpregress) app
3. sopanha
- L1, M1, XS2
- add benner
- add termcodition Eticket
- fix bug when can't get image and solving error overflow
- delete debug
4. vaneath
- commisioner 
- XS1(inreview), S1
- create feed below homepage to list all feeds
- create one column call service type (1 week)

app
- XS 2, S2, M1 

4. panha
- Commissioner 
S2, 
- App (M)
- handle notification when it push and show 
- need to alert notification below start event (ex: 10 minutes) 

5. sreymoch
- App L (WIP)
- work on multi service section

6. sokleng
- Commissioner
- L (WIP), L(WIP)

7. nenghak
- XS, L(WIP)

**Comment by theachoem** [comment]
a hotel does not render rooms

Meeting:

Sreyleak:
- M1: (add product to taxon)
- M2: subtitle to event)

Sopanha:
- L1 (affilicate banner)
- M1 (term condition)
- XS2 (overflow image)

Vaneath:
- S1 (merged) - clear cache home section
- XS (in review)
- Doing new backend feed (#1091)
  - Column for service type
  - 1 week (next week demo)
- XS2, S2, M1

Panha:
- XS x 2 (notification bugs)
- M (mobile)
- make sure bulk marketing work.
- local push (turn on/off upcomming)

Sreymoch:
- Multiple service api

Sokleng:
- L2 (both wip)
- problem:
  - divide tasks (solved)

Nenghak:
- XS
- Cache with Hive (wip)

AMA:
- Effective time management is crucial for a software developer aiming to become a senior developer
- Flutter Matrix4, Perspective Projection

## Reference
- https://codelabs.developers.google.com/codelabs/flutter-flame-brick-breaker
- https://medium.com/flutter-community/advanced-flutter-matrix4-and-perspective-transformations-a79404a0d828
- https://en.wikipedia.org/wiki/Rotation_matrix
