### ISSUE TITLE
Weekly DEV Team Meeting | 14 Feb 2024 #1094

### ISSUE THREAD

**Issue by nenghakheng** [channainfo/commissioner#1115]
# Weekly Dev meeting 14/02/2024

- Panha :
    - L, ecommerce
        - use package, firebase
- Sokleng :
    - 2 L , 1031 and 1064
    - 2 S, 1101 and 1105 (rspec)
    - Doing rspec on pie-chart query
    - not focusing on filter date
    - doing cluster for age (pie-chart)
        - convert number to category (16>22 = adult)
    - Pre-calculate (prioritise)
        - might not be accurate
        - quantity lineitems
    - set boundaries, what is the most valuable for the implementation
    - publish - subscribe (pub-sub)
        - API level
        - solidius is implementing
        - create service
        - similar to notifier in flutter
    - background job (not an option)
        - difficult to scale
        - inefficient
- b SreyLeak
    - M 1145, M 1157 (in review)
    - Design is guideline
    - engage more with UI
    - fix hotel and integrate with section (vaneath)
- Vaneath
    - app :
        - 1174 xs
        - 1161 L (WIP)
    - Commissioner:
        - 1110 L, bitwise dynamic section
        - creating filter
        - tab content is separated
        - use select box to filter
        - create new tab on sidebar (homepage setting) and add sub tab there
        - default general
        - clear cache section is good but confusing
        - load homepage must be cached
        - specify domain to cache
- b Sreymoch
    - homepage appbar (app)
    - fix the grid (3/4), avoid (5/2) (6/1)
    - use grid layout
    - use see more services
- b Panha
- Hak
    - **Close #1109 cache api response using hive**
    - **close #1156 cache lineitems api for ticket booking details**
    - **close #1163 cache qr code image in order completed widget and upcoming widget**
    - WIP **Add incoming events section for operator screen #1168**
    - cache
        - only fields needed
        - server already cached
        - never complete product

- AMA :
    - Release management is important
    - Semantic Versioning
        - 1.0.2
            - Major - 1. for major change of the app such as change UI, technology
            - Minor - .0. add new features
            - Patch - .2 for fix bugs release
        - Github tag (git flow)
            - git checkout master
            - git tag 1.0.0
            - git push origin
            - set up (don’t depend on machine but on the project)
                - node
                - flutter
    - JsonAPI

**Comment by theachoem** [comment]
@nenghakheng good note, but title should be last meeting issue number instead. In this case, it is #1094

**Comment by theachoem** [comment]
- Dynamic section
- Event (checkin & dashboard)
- KYC (confirmed badge)
- Blockchain (push)


Panha: cm-market-app
- L: analytics
   - document

Sokleng: commissioner
- 2L: 1031, 1077
  - post man
- 2S: 1101 & 1105 
- query pie charts
  - Age
- pre-caculate:
  - publish/subscribe in solidius
  - think of change notifier of flutter.
  - or background job.

Leak:
- subtitle (M)
- hotel search M

Vaneath:
- cache static key.

Sreymoch:
- homescreen
  - image
  Retry later 423

Nenghak:
- Only store neccessary
- Cache is partial when neccessary
- How

AMA
- PR take lot of time
- Release management
- Tag:
  - 4.0.1
  - 5.0.0
  - 6.0.0
