### ISSUE TITLE
Weekly DEV Team Meeting | 21 Feb 2024 #1115

### ISSUE THREAD

**Issue by SreyMochOrng** [channainfo/commissioner#1150]
- SreyLeak
   + Size S2 M1 (S1 inprogress)
   + 
- Panha 
  + M1 (app)
  + S1 (commissioner)
  + google calendar 
  + push before 1 hr and 1 day

- Vaneath
  + s1 xs1 (app)
  + xs1 s3 M1 L1(WIP) (commissioner)

- sokleng
  + xs2 M1 s1 s1(WIP)

- Sreymoch
  + M1 (app)

- NengHak
  + M3 xs1

**Comment by theachoem** [comment]
Leak:
- M1, S2, S1 (WIP)

Panha:
- Notfication reminder

Vaneath:
- crop S
- KYC confirmation S
- Remove KYC from create product
- MPTC

Sokleng:
- 

Thea
- Product price

Sreymoch:
- M

Nenghak
- Chart
- Change color for VIP

Todo:
- Backend to mark user as VIP
- Guests controller to edit VIP 
- Focus on price
- Province KYC

Other:
- Wishlist (leak)
- Review/Rating
- check:
  - spree_review & vtenh review
  - how amazon suggest book?
- 2 scope:
  - Review: let user input text & rate
  - Rating: sidekiq job to pre-caculate rating. which to suggest?

- Panha: Rating
- Vaneath: Reivew
- Sreyleak: Wistlist API
- Sreymoch: UI for above
- Dashboard (sokleng + nenghak)

OOP
- Ruby
- Flutter: Mixin
- Java: interface

**Comment by LengTech11** [comment]
Noted:
-after complete and cancle decide the JOB Run or not ( rails polymorphic )
-polymorphic id type make it ( Checkable can be product, taxon)
-rails casts he teach and inspire alot
Join taxon and classification filter taxon that kind event
make should user.event join with classification filter by event 

api of pie chart should return with Product

Update new API: 
	Sent Only 1 request in list event screen

Next:
- Can update guest to VIP
and have attr that can update entry to VIP
Guest controller under Event
Product KYC
KYC provine
