### ISSUE TITLE
Weekly DEV Team Meeting | 28 Feb 2024 #1150

### ISSUE THREAD

**Issue by vaneath** [channainfo/commissioner#1166]
+ Sreymoch: 1213 M App Merge, 1226 M Inprogress, Problem: still having issue on ngrok, social auth service
+ Sreyleak: 1214 S App Merge, 1229 M In progress, Probelm: api call flow, task unclear
+ Panha: 1158 commissioner Merge, 
+ Nenghak: 1215 S App, 1222 M App, 1107 L App
+ Sokleng: 1152 S commissioner, 1161 M commissioner, 1162 xs commissioner, 1164 s commissioner, all Merge, Problem: struggle with return total count api, Suggesttion: add new table that has classification and call that new class instead instead of looping with query
+ Vaneath: Sugguestion: try not to use vertical input field in app, bottom sheet show guest info in booking

**Comment by vaneath** [comment]
## Vaneath Task

+ Commissioner: 1149 L (Merged)
+ App: 1227 L (In Review)

**Comment by LengTech11** [comment]
DONE :
PR : 
 -1152 ( API S)
-1161 ( API M )
-1162 ( API XS )
-1164 (API S)

DONE
Issue :
bi_reports TEDxPhnomPenh 2024 in production #1165 ( get guest info and order number quantity price )

Note & sugguest : 
	should build classification or find first than call it
	should refactor classification_ids avoid not to use (classification_ids)
	paginate make in controller or query
	should avoid query in serializer

**Comment by vaneath** [comment]
### Each person should talk at maximum of 8-9 mins
### 1 hour for meeting

**Comment by theachoem** [comment]
- start at
- reminder before
- attribute type extension (family and child)
- event product tables
- paginate in dashboard_crew_event_query instead.

- next: 1hr, maximum, panha
- 9mn per person
- note questions beforehand
- design for web (similar twitter + fb)
- video
