### ISSUE TITLE
Weekly DEV Team Meeting | 06 Mar 2024 #1166 

### ISSUE THREAD

**Issue by Thornsopanha** [channainfo/commissioner#1192]
## Weekly DEV meeting 
------

### Panha 

**Commissioner**
- Pull Request 1172: Size `S`

**Cm Market App**
- Pull Request 1172: Size `M`

### Vaneath

**Commissioner**  
- Pull Request 1173: Size `S`
- Pull Request 1184: Size `XS`
- Pull Request 1188: Size `S`

**Cm Market App**
- Pull Request 1227: Size `L`
- Pull Request 1246: Size `M`
- Pull Request 1236 (`WIP`): Size `S`

### SreyLeak

**Cm Market App**
- Issue 1229 linked to Pull Request 1230: Size `L`

### NengHak

**Cm Market App**
- Pull Request 1107: Size `L`
- Pull Request 1233: Size `M`

### SreyMoch

**Cm market app** 
- Pull Request 1239: Size `M`

### Sopanha

**Cm Market App**
- Pull Request 1232: Size `L` (renamed `uid` to `userId`)
  > Note: unset user id when user is signed out 
- Pull Request 1245: Size `M`
  > Integration of API Bookmebus 

### Sokleng 

**Commissioner** 
- Pull Request 1178: Size `M`
- Pull Request 1180: Size `XS`
- Pull Request 1185: Size `S`
- Pull Request 1189: Size `M`

**Comment by theachoem** [comment]
Panha what to do after:
- User come in, user expect to "Remind me"
- Option Value still display on mobile
- Event data table

Vaneath:
- Move to migration
- Insert bulk (1 transaction)
- Country flag (app level, map with permalik)

Sreyleak:
- After this, talk with sreyleak how flow work.

Nenghak:
- No problem
- Work on test case
- Enhance UI
- Expect no much bug next week
- Scan color base on entry type.

Sreymoch:
- Google
- Login with apple

Panha:
- uid to userId
- destroy user (unset property)
- After afflicate then bus integration

Sokleng:
- Export on admin/guest
- Loop detect in test (extract to readme)
- Fixing issues:
 - Use "should" less in test case
 - If can't reproduce, don't do it. Always make sure to reproduce.
- Next avocado

- Conscientious
- Voting system with blockchain
- Score

AMA:
- Pivotal tracker
- Spreedsheet
