### ISSUE TITLE
Weekly DEV Team Meeting | 27 Mar 2024 #1236

### ISSUE THREAD

**Issue by LengTech11** [channainfo/commissioner#1268]
# COMMISSIONER

VA NEATH  

- PR 1262 Enchance XS
- PR 1263 M
- PR 1265 XS
- PR 1247 (WIP ENCHANCE L next write spec )
    - [ ]  should export all
    - [ ]  give params event_id
    - [ ]  simplfy to table
    - [ ]  use polymophic
    
**Sokleng**
- **PR 1245 (API XS)**
- **PR 1248 (API S)**
- **PR 1252 (enchance XS)**
- **PR 1253 (enchance XS)**
- **PR 1254 (enchance XS)**
- **PR 1235 (backend L) from last week**

# **APP**

**B SREY LEAK**  

- PR 1249 L
- PR WIP 1230 L
    - NEXT Step
    - [ ]  Detail
    - [ ]  suggest put it at home screen

**SOPANHA**

bookmebus-flutter 

- PR 568 Enchance S

bookmebus/flutter_facebook_sdk

NEXT STEP

- [ ]  Build and Test it well
- [ ]  Test Payment

**NengHak**

**PR 1291 (S)**

**PR 1299 (xs)**

**PR 1295 (XS)**

**PR 1293 (M)**

**Comment by Sreyleak-Deth** [comment]
27/03/2024

- vaneath
PR 1261 (XS)
PR 1263 (M)
 menu check-in 
PR 1265 (XS) 
PR 1247 (WIP) 

- sreyleak
PR 1248 (L)
PR 1229 (L WIP)

Comment
 - Call to action and move it to home page
 - No need to show the empty wished-item

- panha (BookMeBus)
PR 567 (S) enhancement link is have app redirect to app store if not open on web
PR  Update SDK version 

- sokleng 
PR 1244 (XS) add option to line-Item, 
PR 1246 (S) enhance pie-chart 
PR 1249 (XS) 
PR 1250 (XS)
PR 1251 (XS)
PR 1232 (L) 

- nenghak
PR 1288 ()
PR 1295

**Comment by LengTech11** [comment]
## Notes

test make sure it cache or not
public activity
show qr order or line_item
should look for error log and ENV AWS

## Next Steps
show info and have link to click go to website or bookmePlus app
send email and design email (not urgent)
- push automatic
- send notification for specific email
