### ISSUE TITLE
Implement ACL

### ISSUE THREAD

**Issue by channainfo** [channainfo/commissioner#195]
Implement an Access control list in our user system.

- https://github.com/bookmebus/avocado/commit/a67fe8288fdcb5a39f2d17b061da5e4d8fa41a53
- https://github.com/bookmebus/avocado/commit/dac6e8b6a27d070876a3aee2df47ed9cdccf4239

**Comment by theachoem** [comment]
Reference:
- https://github.com/varvet/pundit

**Comment by theachoem** [comment]
- Manually construct for merchant role
- Under merchant scope
- Simplify only for subscription
- Add field to know if role for merchant.
