### ISSUE TITLE
Implement Reuse Guest

### ISSUE THREAD

**Issue by LengTech11** [channainfo/commissioner#1968]
### Task BreakDown

- [ ] Create SavedGuests Table and CRUD Saved Guests: https://github.com/channainfo/commissioner/pull/1981
- [ ] Delegate SavedGuests Fields when Cart Guest want to browse SavedGuest

### User story

As a user, I want to save guest info after filling out the information on the guest info screen so that I don't need to fill out the form again when I buy other products.

### acceptance criteria
- Allow users to browse the quest info where they store the information
- Allow users to store the guest info in somewhere in the app
- Always give the default and auto-filled for users when they arrive at the "guest info screen"
- Allow to delete and update info
### The goal is to allow users to reuse all the saved guest fields they have previously created when they click to select an existing saved guest.
<img src="https://github.com/user-attachments/assets/e585714a-c062-4111-b057-b46b907c1360" alt="reuse_guest_erd" width="500"/>

### 1/ Create Saved Guests UI
<img src="https://github.com/user-attachments/assets/d74e532d-d0f8-4ba1-b4fd-31988f192ab2" alt="Screenshot 2024-09-26 at 4:11 PM" width="500"/>

### 2/ User has the option to create a new `cm_guest` or browse the saved guest to reuse the guest information.
<img src="https://github.com/user-attachments/assets/2a4518b8-8a00-45c8-8f98-667477205900" alt="Screenshot 2024-09-27 at 9:34 AM" width="500"/>

### 3/ If the saved guest field does not fulfill the KYC requirements, the user needs to complete the required KYC fields.
<img src="https://github.com/user-attachments/assets/5dcd6793-29d2-4de2-9bba-da9a70e70c8b" alt="Screenshot 2024-09-27 at 9:35 AM" width="300"/>

**Comment by theachoem** [comment]
Let display all columns for cm_guests & cm_saved_guests. Show relationship to event, line item, and check in as well.

**Comment by LengTech11** [comment]
### Saved Guest Discussion 16/Oct/2024

Create new issue to remove guest from cm_IdCards
- Rename saved guest to template_guest
- Cm_Guest avoid remove Use Soft Delete paranois
- Create RakeTask for Migration split it into micro to run task
