### ISSUE TITLE
Weekly Dev Team Meeting | Oct 30, 2024 #2026

### ISSUE THREAD

**Issue by SreyMochOrng** [channainfo/commissioner#2034]
### Commissioner
- [Link access to design](https://www.figma.com/design/cZ2xMXh7s4GCajMHXZYW6i/BMP?node-id=5-211&node-type=canvas&t=vnzCywRPtgEpMHs5-0)
- https://github.com/channainfo/commissioner/issues/2033

**Comment by nangdypanhar** [comment]
#  Nangdy Panhar
### App :
- https://github.com/bookmebus/cm-market-app/pull/1892

**Comment by hulsambath** [comment]
## Sambath
### Cm-Vendor-App
- [Setup Flutter Launcher Icon](https://github.com/bookmebus/cm-market-vendor-app/pull/19)
- [Setup Flavor App](https://github.com/bookmebus/cm-market-vendor-app/pull/21)
- [Setup Splash Screen](https://github.com/bookmebus/cm-market-vendor-app/pull/23)
- [Move project to a folder](https://github.com/bookmebus/cm-market-vendor-app/pull/25)
- [Setup base api in folder core, folder core in the same folder with cm-vendor-app](https://github.com/bookmebus/cm-market-vendor-app/pull/27)

**Comment by SSambo12** [comment]
## Source Code

- https://github.com/phana25/EcommerceApp_Rails.git

## Live Demo

**Comment by panhachom** [comment]
### Chom Panha
- https://github.com/bookmebus/spree_vpago/issues/204

**Comment by Sreyleak-Deth** [comment]
## Sreyleak

### App
- https://github.com/bookmebus/cm-market-app/pull/1566

**Comment by Thornsopanha** [comment]
# PANHA
- BMB App doesn't display trip as indirect or transfer
https://github.com/bookmebus/bookmebus-flutter/issues/595
- Cange UI flow on Banner 
https://github.com/bookmebus/bookmebus-flutter/pull/592
