### ISSUE TITLE
Weekly Dev Team Meeting | Nov 6, 2024 #2034

### ISSUE THREAD

**Issue by mengthong-ly** [channainfo/commissioner#2044]
## Weekly Meeting 

Please Drop your previous Week work

**Comment by hulsambath** [comment]
## Sambath
### Cm-Vendor-App
Task:
- [Setup base model](https://github.com/bookmebus/cm-market-vendor-app/pull/29)
- [Setup Api Interceptor](https://github.com/bookmebus/cm-market-vendor-app/pull/32)
- [Setup Api Client](https://github.com/bookmebus/cm-market-vendor-app/pull/33)

**Comment by nangdypanhar** [comment]
## Nangdy Panhar
### Commissoner : 
#2046 : add nearby places suggestion

**Comment by SreyMochOrng** [comment]
## Orng SreyMoch                              
### Commissioner
- #2033 
- Design Order Cancellation Email
- Explore JWT(JSON Web Token)

**Comment by panhachom** [comment]
### Panha Chom
- https://github.com/bookmebus/spree_vpago/issues/204

**Comment by Sreyleak-Deth** [comment]
## Sreyleak

### App
 - Update UI on screen Upcoming and Previous:
  - https://github.com/bookmebus/cm-market-app/pull/1566
 
### Commissioner
 - #2043

**Comment by mengthong-ly** [comment]
## Mengthong

**Comment by LengTech11** [comment]
## Houng Sokleng
WIP PR : https://github.com/bookmebus/cm-market-app/pull/1809

**Comment by SSambo12** [comment]
## Koy Sambo

- Install and setup the project
