### ISSUE TITLE
Order Invoice View

### ISSUE THREAD

**Issue by panhachom** [channainfo/commissioner#253]

**Comment by theachoem** [comment]
<img width="266" alt="image" src="https://user-images.githubusercontent.com/29684683/226849935-11a0ebcb-214f-4cd7-89c1-ef98b69072ca.png">

**Comment by theachoem** [comment]
To create an invoice for an order in Ruby on Rails, you can follow these general steps:

1. Define the invoice model: Create a new model called "Invoice" with attributes such as invoice number, date, total amount, customer information, and order information.

2. Define the invoice controller: Create a controller for the invoice model with actions such as "create" and "show" to create new invoices and display existing ones.

3. Generate the invoice: To generate the invoice, you will need to retrieve the relevant order information such as the customer name, shipping address, order items, and prices.

4. Calculate the total amount: Calculate the total amount of the order by summing up the prices of all the order items.

5. Save the invoice: Save the invoice to the database with the relevant information.

6. Send the invoice: Send the invoice to the customer through email or by providing a download link to a PDF file.

Here's some sample code to create an invoice:
```rb
# Define the Invoice model
class Invoice < ApplicationRecord
  belongs_to :order
  validates :invoice_number, presence: true, uniqueness: true
  # Other validations and methods here
end

# Define the Invoice controller
class InvoicesController < ApplicationController
  def create
    # Retrieve the order information
    @order = Order.find(params[:order_id])
    
    # Calculate the total amount
    @total_amount = @order.items.sum(:price)
    
    # Generate the invoice
    @invoice = @order.invoices.build(invoice_params)
    @invoice.total_amount = @total_amount
    
    if @invoice.save
      # Send the invoice to the customer
      InvoiceMailer.invoice_email(@invoice).deliver_now
      
      redirect_to invoice_path(@invoice), notice: 'Invoice was successfully created.'
    else
      render :new
    end
  end
  
  def show
    @invoice = Invoice.find(params[:id])
  end
  
  private
  
  def invoice_params
    params.require(:invoice).permit(:invoice_number, :date, :customer_name, :customer_email, :shipping_address)
  end
end

# Define the Invoice mailer
class InvoiceMailer < ApplicationMailer
  def invoice_email(invoice)
    @invoice = invoice
    mail(to: @invoice.customer_email, subject: 'Your invoice')
  end
end
```
