### ISSUE TITLE
I didn't receive an email order confirmation after booking

### ISSUE THREAD

**Issue by MenghourLao** [channainfo/commissioner#714]
### Bug Description
I booked the event tickets last evening, but I have not received any emails from BookMe+. After that, I went to the backend to check and clicked on approved on the backend, but I still did not get anything.

### Here my order:
![Screenshot 2023-10-16 at 6 35 47 PM](https://github.com/channainfo/commissioner/assets/76026690/8da5ea97-d06c-4abc-bfaf-1bbbf1be55fe)

**Comment by theachoem** [comment]
<img width="288" alt="image" src="https://github.com/channainfo/commissioner/assets/29684683/85fe5435-a229-4af4-8281-8ac1d6e57078">

 @channainfo
