### ISSUE TITLE
ActionView::Template::Error: undefined method `qr_image_url' for #<ActionView::Base:0x000000000e1320>

### ISSUE THREAD

**Issue by theachoem** [channainfo/commissioner#729]
![image](https://github.com/channainfo/commissioner/assets/29684683/ea14eb22-6f2a-4f82-a09f-e46a61a732aa)

**Comment by kimsrung** [comment]
could be fix by this https://github.com/channainfo/commissioner/pull/719/files

**Comment by theachoem** [comment]
I see it in sidekiq, maybe it old failed jobs. But let see it again
