### ISSUE TITLE
Facebook Data Deletion Request Callback

### ISSUE THREAD

**Issue by theachoem** [channainfo/commissioner#740]
- https://developers.facebook.com/docs/development/create-an-app/app-dashboard/data-deletion-callback
- https://developers.facebook.com/apps/327812796472338/settings/basic/?business_id=119136952108127

**Comment by theachoem** [comment]
@channainfo

**Comment by channainfo** [comment]
A Sample content: https://www.finmonster.com/data-deletion-instructions

We need to screenshot the step in the app.

**Comment by theachoem** [comment]
@panhachom you can add them in CMS like provided examples.

**Comment by panhachom** [comment]
<img width="1512" alt="image" src="https://github.com/channainfo/commissioner/assets/92453740/a3573658-c620-4806-a9fd-0e3f2119dd79">
